.circleci/config.yml
This _should_ make it such that CircleCI runs on tag builds (and thus can push to npm).
=> Perform the entire CircleCI workflow on tags.

system-test/storage.js
Remove comment about requester pays system tests being skipped as they're now enabled and passing since [PR#42](https://github.com/googleapis/nodejs-storage/pull/42). The fix was to grant roles/Storage.Admin at project-level IAM Policy instead of bucket-level IAM Policy.
There will be a follow-up review in two weeks to assign this role only at Bucket-level to allow for Storage.buckets.delete operation which failed before. No code should be necessary.
=> [Requester-Pays] Remove skip comment for Requester Pays system tests. 

.circleci/config.yml
This makes pre-release version bumps work.
=> Switch npm install and link order.

src/file.js
=> Fix docs typo

src/bucket.js, src/index.js
RE: #26 
It was pointed out in #26 that our JSDocs say `getBuckets()` and `getFiles()` return an `apiResponse` argument to the callback/promise. However, that is only true when `options.autoPaginate = false`. To avoid confusion, it seems best to remove the line about `apiResponse`, and instead only show that it exists in the example documentation for `autoPaginate`.
=> docs: un-document `apiResponse` from list operations.

system-test/storage.js
This adds tests that confirm the download method works without authentication.
(It did not previously, it will after this)
=> Test un-authenticated downloads and uploads.

system-test/storage.js
These system tests were previously failing because the automatic project ID insertion was putting in the wrong project ID... the one from the `bucketNonWhitelist` instance.
=> Get the full Topic name.

samples/system-test/encryption.test.js
We've been getting an error on CI, and I think this should fix it.
Error: https://circleci.com/gh/googleapis/nodejs-storage/2149
=> samples: tests: Test stdout, not stderr.

.circleci/config.yml
Prevent rebuilding `grpc` by running CI tasks as non-root user. Details [here](https://github.com/ForbesLindesay/tar-pack/issues/35).
=> chore: run CI as non-root user

system-test/storage.js
A 404 error for an object used to return an error message that said something like "Not found". It now returns "No such object". I removed our test that checked for specific messaging, and instead just confirm that the code is 404.
=> Fix stale test.

package.json, src/file.js, test/file.js
=> Smart-start resumable uploads.

src/file.js, test/file.js
Fixes #167
This uses the native `url` module to build the URL, which I think is less brittle than the existing string-building method.
=> properly encode signed URLs

src/bucket.js, test/bucket.js
=> don't require contentType for bucket.combine

system-test/storage.js
CI has been failing: https://circleci.com/gh/googleapis/nodejs-storage/4098.
=> Fix system tests.

src/notification.js
Part of #173 
First of the 6 PRs to come - decided to break the refactor into pieces by class, since the whole refactor is huge.
52c2875 - 
- rewrite function constructor as class
- use `extends` instead of `util.inherits` to extend ServiceObject class
- internalize all `.prototype` methods into class
7b73a4a - use arrow syntax instead of mapping `self = this`
=> refactor(es6): Notification: es6 class

src/acl.js
Part of #173
ab75f38
- rewrite function constructor as class
- use `extends` instead of `util.inherits` to extend ServiceObject class
- internalize all `.prototype` methods into class
203338e
- use arrow syntax instead of mapping `self = this`
=>  refactor(es6): Acl: use es6 class

src/file.js
Part of #173 
Note:
The constructor => class conversion is pretty much 1-to-1, except for one special change in the constructor:
Pre-ES6 constructor code
```javascript
function File(bucket, name, options) {
...
Object.defineProperty(this, 'name', {
enumerable: true,
value: name.replace(/^\/+/, ''), // Remove leading slashes.
});
...
```
This is replaced by:
```javascript
class File ...
constructor(bucket, name, options) {
...
name = name.replace(/^\/+/, '');    /** normalizing name first **/
...
this.name = name;    /** then simply assigning it to the new file object **/
...
}
...
```
https://github.com/googleapis/nodejs-storage/pull/238/files#diff-de48719f755e5f35fe85c57bf1830fc1R100
=> refactor(es6): File: use es6 class

src/acl.ts, src/bucket.ts, src/channel.ts, src/file.ts, src/index.ts, src/notification.ts
Another PR to address tsc compilation errors, specifically errors that takes the form:
> Property 'x' does not exist on type 'y' of z.
=> Typescript: add 'any' type to suppress compiler error

src/acl.ts, src/bucket.ts, src/file.ts, src/iam.ts, src/index.ts, src/notification.ts
`tsc` compiles successfully following this PR.
This PR addresses the following (and more):
- optional callback?
- type cast to `any` if incompatible types can't easily be fixed
- fixes imports/exports
- comparing `Date`'s using `.valueOf()`
=> Typescript: misc. fixes to make tsc happy

test/bucket.ts, test/file.ts, test/notification.ts, tsconfig.json
Finish converting tests to typescript by:
- (Temporarily) disable `noImplicitThis`
- Cast to `any` when tsc complains
- Add optional (?) to arguments where # of arguments mismatches
- Fix date comparison by calling `Date#.valueOf()` to get milliseconds from Date object and compare the two numbers
- Request fakes to use class syntax and Proxy hack to allow creating an object without `new`
=> Typescript: tests (2)

test/acl.ts
Fix test/acl.ts to make the test pass.
Specifically, src/acl.ts now has 2 named (es6)-exports and `AclRoleAccessorMethods` is no longer a member of the Acl constructor.
=> refactor(ts): make test/acl.ts pass

test/acl.ts, test/bucket.ts, test/channel.ts, test/file.ts, test/iam.ts, test/index.ts, test/notification.ts
- convert all anonymous functions to fat arrow =>
- fat arrow functions using `arguments` function-scoped argument is fixed (since arrow function doesn't support `arguments`) with ...args splats
- anonymous functions referencing the object's `this` value is changed to use `extend(obj, { overriddenMethod() { // implementation });`
=> Typescript: tests function() to arrow =>

src/bucket.ts, src/index.ts, test/acl.ts, test/index.ts
It's really hard and non-idiomatic to export Storage as module export
with typescript and using Proxy-hack to make Storage instantiable
without new is also hacky and doesn't expose proper types to consumer of
the client.
**BREAKING CHANGE**
```
✔ const {Storage} = require('@google-cloud/storage');
𝘅 const Storage = require('@google-cloud/storage');
// Storage cannot be instantiated without new:
𝘅 const storage = Storage();  // deprecated
✔ const storage = new Storage();
```
=> TypeScript: export {Storage} as named export

.kokoro/common.cfg, .kokoro/continuous/node10/common.cfg, .kokoro/continuous/node6/common.cfg, .kokoro/continuous/node8/common.cfg, .kokoro/docs.sh, .kokoro/lint.sh, .kokoro/presubmit/node10/common.cfg, .kokoro/presubmit/node6/common.cfg, .kokoro/presubmit/node8/common.cfg, .kokoro/samples-test.sh, .kokoro/system-test.sh, .kokoro/test.sh
This should fix `ci/kokoro: lint`, where `npm install` fails when running under `root`.
=> build(kokoro): run docker as user node

package.json, samples/encryption.js, samples/package.json, src/file.ts, system-test/storage.js, test/file.ts
Now that we throw on deprecation warnings, this isn't needed.
=> Remove safe-buffer

src/bucket.ts, test/bucket.ts
Fixes #170 
This cleans up the fragments of a gs:// URL, should the user provide one to the Bucket constructor.
=> fix: remove trailing slashes from bucket name.

package.json
Somehow we got away without including request as dependency. Making
that implicit so we don't run into problems when pubsub updates.
```
npm ls request
@google-cloud/storage@2.0.0 /Users/franzih/code/gcp/nodejs-storage
├─┬ @google-cloud/pubsub@0.19.0
│ ├─┬ @google-cloud/common@0.16.2
│ │ ├─┬ google-auto-auth@0.9.7
│ │ │ └── request@2.88.0  deduped
│ │ ├── request@2.88.0  deduped
│ │ └─┬ retry-request@3.3.2
│ │   └── request@2.88.0  deduped
│ └─┬ google-auto-auth@0.10.1
│   └── request@2.88.0  deduped
├─┬ codecov@3.0.2
│ └── request@2.88.0
└─┬ gcs-resumable-upload@0.12.0
└── request@2.88.0  deduped
```
Prerequisite for https://github.com/googleapis/nodejs-storage/issues/207 so we can switch to smaller HTTP dependency.
=> fix: make dependency on request explicit

src/bucket.ts, src/file.ts, src/index.ts, system-test/storage.js, test/bucket.ts, test/file.ts
- Tests
- https://docs.google.com/document/d/1wRpiAxTHZoypR1NLVP97Cj0WCGVKx43Tivso0xXhyEA/edit?ts=5b60f543#
- https://www.googleapis.com/discovery/v1/apis/storage/v1/rest
This introduces new behavior:
- **bucket#lock()**
Lock a previously-defined retention policy. This will prevent changes to the policy.
- **bucket#removeRetentionPeriod()**
Remove an already-existing retention policy from this bucket.
- **bucket#setRetentionPeriod(durationInSeconds)**
Lock all objects contained in the bucket, based on their creation time.
- **file#getExpirationDate()**
Get a Date object representing the earliest time this file will expire.
---
Additionally, `bucket#getMetadata()`, `bucket#setMetadata()`, `file#getMetadata()`, and `file#setMetadata()` are available if users wish to interact with the raw …
=> Support Bucket/Object lock operations

src/file.ts, test/file.ts
Fixes #355
cc @Alfredo-Delgado
=> fix: copy(): Use correct destination file name in URI

samples/files.js
Found via https://twitter.com/iaincollins/status/1040247045246930946
"I ran into the Google Cloud SDK documentation (and code examples!) using MM-DD-YYYY yesterday"
Docs state:
"A timestamp when this policy will expire. Any value given is passed to new Date()."
=> samples: don't use USA formatted dates for expiry

CHANGELOG.md
=> docs: Explain `Bucket#upload()` still exists

.circleci/config.yml, synth.py, system-test/storage.ts
This seems to have fixed the system test failures running CircleCI.
Let's get this in so we can debug the Kokoro system test failures.
=> fix(tests): fix system tests

samples/README.md, samples/bucketLock.js, samples/files.js, samples/system-test/bucketLock.test.js, src/bucket.ts, src/file.ts, src/index.ts, system-test/storage.ts, test/bucket.ts, test/file.ts
- Tests
- https://docs.google.com/document/d/1wRpiAxTHZoypR1NLVP97Cj0WCGVKx43Tivso0xXhyEA/edit?ts=5b60f543#
- https://www.googleapis.com/discovery/v1/apis/storage/v1/rest
This introduces new behavior:
- **bucket#lock()**
Lock a previously-defined retention policy. This will prevent changes to the policy.
- **bucket#removeRetentionPeriod()**
Remove an already-existing retention policy from this bucket.
- **bucket#setRetentionPeriod(durationInSeconds)**
Lock all objects contained in the bucket, based on their creation time.
- **file#getExpirationDate()**
Get a Date object representing the earliest time this file will expire.
---
Additionally, `bucket#getMetadata()`, `bucket#setMetadata()`, `file#getMetadata()`, and `file#setMetadata()` are available if users wish to interact with the raw …
=> feat: Support Bucket/Object lock operations

src/file.ts
The value in the example five lines up is 'world', so this line should match that.
=> Minor docs correction

package.json
This turns TypeScript types back on. Fixes #443. Fixes #384.
=> fix: re-enable typescript types

src/bucket.ts, system-test/storage.ts, test/bucket.ts
This introduces one method, `bucket.addLifecycleRule(rule, [options], [callback])`:
```js
bucket.addLifecycleRule({
action: 'delete',
condition: {
age: 365 * 3 // Specified in days.
}
});
```
```js
bucket.addLifecycleRule({
action: 'delete',
condition: {
age: 365 * 3 // Specified in days.
}
}, { append: false });
```
```js
bucket.setMetadata({ lifecycle: null });
```
=> Introduce Object Lifecycle Management

src/file.ts
Fixes #497 
Currently, the getSignedUrl type is returning GetSignedPolicyResponse. It should be GetSignedUrlResponse
=> Fixes getSignedUrl Return Type

src/file.ts
Addresses question raised in #274 where @eleith notice unpredictable results when File.setMetadata is called in parallel.
fixes #274
=> docs: File#setMetadata in parallel results in unpredictable state

src/storage.ts, system-test/storage.ts
Fixes #346 
> - [ ] Tests and linter pass
I did not check.
> - [ ] Code coverage does not decrease (if any source code was changed)
I did not check.
> - [ ] Appropriate docs were updated (if necessary)  
I have not read all the docs, but the comments already suggested that this was possible, now the code is in harmony with them.
=> fix(ts): Update bucket options types

.kokoro/setup-vars.sh, system-test/storage.ts
Contains the following asserts:
- General Bucket Policy Only assertions
- Object acl get or update fails w/ 400
- Insert a new bucket with Bucket Policy Only Enabled.
- Verify that objects can be written to the bucket by project Owners and Editors without any further configuration
- Verify that default object acl and object acls are preserved
- Create a bucket
- Insert an object
- Enable BPO
- Disable BPO
- Check that the object's ACLs are still there
=> test: Bucket Policy Only related system test

package.json, src/acl.ts, src/bucket.ts, src/file.ts, src/iam.ts, src/notification.ts, system-test/storage.ts, test/bucket.ts, test/file.ts
- ~~https://github.com/googleapis/nodejs-common/pull/349~~
- ~~https://github.com/googleapis/gcs-resumable-upload/pull/167~~
- ~~https://github.com/googleapis/gcs-resumable-upload/pull/171~~
- ~~https://github.com/googleapis/nodejs-common/pull/353~~
- ~~https://github.com/googleapis/nodejs-common/pull/356~~
I took the code from @JustinBeckwith out of #556.
=> Upgrade nodejs-common

package.json
Fixes #27 
This updates @google-cloud/common, which includes the `timeout: 0` fix for streaming file uploads.
=> deps: update @google-cloud/common

src/file.ts, test/file.ts
Fixes #613 
If the user provides an invalid Date to `file.getSignedPolicy()` or `file.getSignedUrl()`, we will now throw.
=> fix: getSigned(Policy|Url) throws if expiration is invalid Date

src/file.ts, test/file.ts
Fixes #602
- `npm install stephenplusplus/nodejs-storage#spp--602`
=> fix: handle errors from file#createReadStream

test/bucket.ts, test/channel.ts
=> tests: fix assertion syntax

.repo-metadata.json
I'm using `nodejs-storage` to test our new `synthtool` README generation, it relies on @busunkim96's meat-information work.
=> docs: add a .repo-metadata.json

samples/buckets.js
When @laylasells and I were walking through these code examples for the first time, we found the magic variables `ASIA` and `coldline` somewhat *magical* 🌠; this pull request adds documentation clarifying the meaning of these values.
=> docs: clarify in docs, the meaning of ASIA and coldline

src/file.ts, test/file.ts
Fixes #566 
To quickly sum up the issue discovered in #566, this works:
- Save file with contents 'a'
- Download file. Contents === 'a'
- Save file with contents 'b'
- Download file. Contents === 'b' 😄
But as soon as it's a public file, it doesn't work:
- Save file with contents 'a'
- Make file public
- Download file. Contents === 'a'
- Save file with contents 'b'
- Download file. Contents === 'a' 😢
I believe what happens when the file is flipped to a public object, we then have to worry about caching. When you update the file, the upstream API's `generation` property is updated as well for the Object record.
So far, I've found three solutions:
- Ensure the file we download will not be cached (`Cache-Control: no-store`)
- Set `Cache-Control: no-transform` on the file's metadata
- Send the …
=> fix: do not download cached files

samples/files.js
It's often the case that a user wants to change the destination name of an object they're uploading, but it's pretty buried in the docs.
=> docs: document destination option

.repo-metadata.json
we use the `api_id` when allowing folks to enable a given API; this last piece of information seems to get us to the point where we can use `.repo-metadata.json` for generating the project README.md.
=> docs: add additional api_id field

src/file.ts, system-test/storage.ts
As discussed, we have been supporting multi-valued headers for v2 signing.
This PR added a system-test to verify the request header is signed assuming header values will be delimited by a single `,` with no spaces between values.
Also added a note in the jsdoc to inform users a request using the signed url must use the same delimiting scheme.
=> test(v2-sign): add multi-valued headers system-test

samples/quickstart.js, samples/system-test/quickstart.test.js
This PR updates the quickstart sample to follow the new Node.js sample rubric:
- The projectId isn't explicitly used, so it's reference was dropped
- The region tag was moved inside of the `main` function
- Added a note asking the developer uncomment the bucketName
- Used an inner async function with the actual code
@bcoe this will fix the issue you had where you needed to add the footer thingy to synthtool. 
@jmdobry is the rubric published anywhere?
=> docs(samples): refactor the quickstart to match the new rubric

.gitignore, .readme-partials.yaml, .repo-metadata.json, README.md, synth.metadata
refs: https://github.com/googleapis/google-cloud-node/issues/2868 this PR regenerates our README using `synthtool` rather than node-repo-tools.
It seems to be most of the way there, one thing that does jump out at me is the description isn't nearly as fleshed out ... I wonder if this grew organically over time; any thoughts about how to auto-generate the README with up-to-date samples, while maintaining a more useful description?
@busunkim96 thanks for all your help on this!
=> docs: new synthtool generated README

package.json, src/bucket.ts, src/channel.ts, src/file.ts, src/notification.ts, src/storage.ts
With the goal of getting master passing, pulls in `@types/node@11.12.4`, as `11.13.0` is currently breaking the build.
This PR brings in this [breaking change](https://github.com/googleapis/nodejs-common/pull/394) which retires the configurable request object (unfortunately this didn't address the error on `master`, because other dependencies brought in `@types/node@11.13.0`.
=> chore(deps): upgrade to newest version of @google-cloud/common

package.json, samples/system-test/test_87aec0b9-4a52-44dc-9ab7-522c4dbf8895.txt, src/acl.ts, src/bucket.ts, src/channel.ts, src/file.ts, src/iam.ts, src/notification.ts, src/storage.ts, test/acl.ts, test/bucket.ts, test/index.ts
As a bonus, drops dependencies on `teeny-request` and `@types/request`
=> fix(ts): improve return types for response metadata

src/file.ts, test/file.ts
Fixes #671
add validation for `action` parameter.
=> fix: validate action of getSignedUrl() function

package.json
Tests are currently failing because `async` is used in a few of them.
_update: @types/protobufjs also needed to be updated._
=> test: async is still used in tests

src/bucket.ts, system-test/storage.ts
test(bucket): location type system tests
docs(bucket): add verbiage about deprecated storage classes
---
Closes #732
=> fix(typescript): make SetLabelOptions optional

src/file.ts
=> docs: add 7 day cap note for v4 duration of getSignedUrl

src/bucket.ts
multi_regional and regional storage classes were marked as deprecated but are actually legacy.
=> docs: update documentation on legacy storage classes

bin/README.md, bin/benchwrapper.js, bin/storage.proto, package.json, src/storage.ts
This PR adds a gRPC server which wraps the storage client library. The methods specified in the proto are read and write, though the only implemented method in this PR is read.
The PR also:
- Adds an `apiScheme?` to `StorageOptions` (alongside `apiEndpoint?`)
- Causes validation: false to actually not do validation, instead of the current behavior in which validation: false always returns a validation error
=> test: add benchmarking wrapper

package.json, system-test/storage.ts
Upgraded `@google-cloud/common` has added original error message with of JSON parsing failure. 
- To check original message is propagating to api response, added system test case for non JSON response body. ( metadata size is too large)
Fixes #170
=> fix(deps): upgrade @google-cloud/common version to show original error message

package.json, system-test/storage.ts
Started to see typescript compilation failed overnight:
```
> @google-cloud/storage@3.1.0 compile /Users/jonathanlui/nodejs-storage
> tsc -p .
system-test/storage.ts:108:1 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/Users/jonathanlui/nodejs-storage/node_modules/nock/types/index")' has no compatible call signatures.
108 nock('http://metadata.google.internal')
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
There hasn't been releases to `@types/nock`, `typescript` or `gts`. So
this is a temporary fix to unblock releasing while we figure out why.
Turns out starting at nock@11.1.0, they [shipped](https://github.com/nock/nock/releases/tag/v11.1.0%40next) their own typescript definition in the package. The types assumed the downstream library …
=> fix(ts): fix nock @~11.0.0

src/file.ts
=> revert: remove unsupported keepAcl param from file#copy

src/file.ts, system-test/storage.ts, test/file.ts
Currently optional param `predefinedAcl` in [file#copy](https://github.com/googleapis/nodejs-storage/blob/916cede255597ca8d605fa48a079d9c6e1e9b17c/src/file.ts#L864) is not utilized properly.
As per docs API expects `[destinationPredefinedAcl](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite)` as part of the qs (not Json).
=> fix: pass predefined acl as destinationPredefinedAcl to qs

src/file.ts, test/file.ts
Currently if user passes same `bucket` object, `file`object, or `fileName` string as the original file, the client will attempt to "copy" (essentially leaving the file in place) and subsequently delete the origin/destination file.
=> fix: file#move do not delete origin file if same as destination

src/bucket.ts, system-test/storage.ts, test/bucket.ts
Fixes #23 
Hello! This adds the `bucket.enableLogging()` shortcut method as discussed in #23.
=> feat(bucket): add enableLogging method

src/file.ts, src/storage.ts, test/file.ts, test/index.ts
Reverts googleapis/nodejs-storage#854. @broady and @JustinBeckwith, I'm reverting this change to align with the new rollout plan to reduce impact.
=> Revert "fix: use storage.googleapis.com for api endpoint"

src/file.ts
=> fix(docs): missing quote in signed url jsdoc

src/file.ts, src/storage.ts, test/file.ts, test/index.ts
Reverts googleapis/nodejs-storage#893
Turns out we want to no fix this and I'm reverting my revert based on discussion with @broady and @crwilcox.
=> fix: use storage.googleapis.com for api endpoint

src/file.ts
One of the comments in the documentation for `createReadStream` has the following content.
> To limit the downloaded data to only a byte range, pass an options object.
And a part of it ('object') is not rendered as a comment in https://googleapis.dev/nodejs/storage/latest/File.html#createReadStream as it is missing a `//`.
=> fix(docs): rendering for createReadStream method in File class

src/file.ts, test/file.ts
Fixes #909
A couple things happened along this journey to fix #909.
I learned that the [configstore](http://gitnpm.com/configstore) `configPath` option isn't for a directory, it's actually the file name. We use that through gcs-resumable-upload to persist metadata about the progress of a resumable upload.
Even though that understanding was wrong, I didn't make any actual code changes in this PR. All I did was rephrase the documentation. Interestingly, the documentation was half-correct when it said "This maps to the configstore option by the same name." So... breaking change? I would not say it is, since code-wise, things behave the same.
Oh, what was #909 about? It's amazingly described, so you could read it just for fun, but to sum it up: when the user gave us a `configPath`, we were …
=> fix: do not check access of configPath

synth.metadata, synth.py
fixes nightly synthtool run (`exclude` should be `excludes`, and takes array).
fixes: https://github.com/googleapis/nodejs-storage/issues/927
=> build: should be excludes not exclude

src/iam.ts, system-test/storage.ts, test/iam.ts
Minimal code changes is involved in this PR.
We map `optionsRequestedPolicyVersion` to `requestedPolicyVersion` so the surface is uniform across products.
=> feat(iam): getIamPolicy to support requestedPolicyVersion

src/file.ts, system-test/storage.ts, test/file.ts
=> fix: skip validation for server decompressed objects

conformance-test/test-data/v4SignedUrl.json, conformance-test/v4SignedUrl.ts, src/signer.ts
`bucket.getSignedUrl` previously generated a URL with a trailing `/` that matched with the old conformance-test spec:
`https://storage.googleapis.com/bucket-name/?query1=...`
But the new conformance-test has no trailing slash.
merge #1066 into `v4-ga` branch first.
=> fix(signed-url): trailing `/` after path before query params

bin/benchwrapper.js, system-test/storage.ts
Fixes #1105 
We've been getting a different (expected) error message on Kokoro vs local development environments. This allows either one to pass the test.
=> test: allow environmentally-conditional errors

src/file.ts
Fixes #1114 
`File#getSignedUrl()` returns what `URLSigner#getSignedUrl()` returns. But, the File method is promisified, which means we actually send back `[resp]`, and not just `resp`. Does this solution make sense?
=> fix(types): wrap GetSignedUrlResponse

src/file.ts, src/signer.ts
VS code complained of duplicate local variable with the referencing to self in #1119. I think this is a little bit cleaner.
=> types: split out SignedUrlResponse

src/bucket.ts, test/bucket.ts, test/testdata/dummylargetestfile.txt
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #1133 
I've added a test case for this by stubbing `fs.stat` - I hope that's ok!
=> fix(bucket): Only disable resumable uploads for bucket.upload (fixes #1133)

src/file.ts, test/file.ts
=> fix(v4-policy): add missing bucket field
