.cloud-repo-tools.json, LICENSE, README.md, package.json
Fixes GoogleCloudPlatform/nodejs-repo-tools#22
Fixes GoogleCloudPlatform/nodejs-repo-tools#23
Fixes GoogleCloudPlatform/nodejs-repo-tools#24
=> Upgrade repo-tools and regenerate.

src/file.js, system-test/storage.js, test/file.js
Fixes #24 
Carried over from https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2581
=> handle validation at the same rate as destination pipe

.appveyor.yml, .cloud-repo-tools.json, README.md, package.json, samples/README.md, samples/notifications.js, samples/package.json, samples/system-test/notifications.test.js, src/bucket.js, src/notification.js, system-test/storage.js, test/bucket.js, test/notification.js
=> PubSub Notifications

src/bucket.js, src/file.js, src/index.js, src/notification.js
=> docs: Correctly define "Requester Pays" terminology.

src/bucket.js, src/notification.js
Blocks publishing the API ref docs for 1.4.x
=> Fix wrong region tag and sample file references.

.gitignore, CONTRIBUTORS, README.md, package.json, samples/README.md, samples/package.json, system-test/.eslintrc.yml
=> Upgrade repo-tools and regenerate scaffolding.

src/acl.js, src/bucket.js, src/file.js, src/iam.js, src/index.js, system-test/storage.js, test/acl.js, test/bucket.js, test/file.js, test/iam.js, test/index.js
=> requester pays

src/bucket.js, src/file.js, src/notification.js
Minor documentation improvement.
@stephenplusplus FYI
=> Indicate userProject is string, not boolean

samples/encryption.js, samples/system-test/encryption.test.js, src/file.js, system-test/storage.js, test/file.js
Fixes #22 
This adds `file.rotateEncryptionKey(newKey, [callback])`.
=> Add file#rotateEncryptionKey().

package.json, src/file.js, src/index.js, system-test/storage.js, test/file.js, test/index.js, test/testdata/privateKeyFile.json
Fixes #39
Depends on:
---
This changes the `getSignedUrl()` and `getSignedPolicy()` methods to use the signBlob API via google-auto-auth.
=> Use signBlob API for getSignedPolicy() and getSignedUrl()

src/file.js, test/file.js
=> Generate signed policy from base64-encoded policy.

samples/files.js, samples/iam.js, samples/requesterPays.js, samples/system-test/files.test.js, samples/system-test/iam.test.js, samples/system-test/requesterPays.test.js
=> Linting per prettier@1.9.0.

src/file.js
=> Attach end event listener to last stream in pipe.

src/bucket.js, test/bucket.js
=> Support for additional request options applied to download request when bucket.upload() is called with URL

src/bucket.js, test/bucket.js
=> Bucket: Remove a leading gs://

src/file.js, test/file.js
=> File#getSignedUrl: Support resumable action.

src/file.js
=> Mention the required scope for `getSignedUrl` and `getSignedPolicy`.

src/file.js
=> docs: add performance note to File#save.

samples/buckets.js
=> Add location and storageClass metadata to createBucket sample

src/bucket.js, test/bucket.js
=> fix: bucket.upload(): return apiResponse

src/bucket.js, system-test/storage.js, test/bucket.js
=> Add `directory` option to `getFiles()`

system-test/storage.js
Fixes https://circleci.com/gh/googleapis/nodejs-storage/3721
=> test fix: There are 3 files in a directory, not 2

package-lock.json, package.json, samples/package-lock.json
@JustinBeckwith Mayday! Our stuff isn't running with @google-cloud/common 0.18.3.
```
$ npm run system-test
run: Executing tests in: C:\Users\sawch\dev\nodejs-storage
run: Running: mocha system-test/*.js --no-timeouts
storage
run: Success! Test finished in 3.34s
```
=> Downgrade common to 0.17.0

package-lock.json, package.json, samples/encryption.js, samples/package-lock.json, src/bucket.js, src/file.js, src/index.js, system-test/storage.js, test/bucket.js, test/file.js
This adds support for KMS.
- Unit tests
=> Introduce KMS

package-lock.json, samples/package-lock.json
Need to update lock files to make the release CI go through.
=> chore: lock files

.gitignore, package-lock.json, package.json, samples/package-lock.json, samples/package.json, src/acl.js, src/bucket.js, src/file.js, system-test/storage.js, test/bucket.js, test/file.js
@JustinBeckwith I updated both dependencies at once, and the system tests. And...:
<details>
<pre>
24 passing (5h)
1 pending
62 failing
1) storage
without authentication
public data
should list and download a file:
Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\sawch\dev\nodejs-storage\system-test\storage.js)
2) storage
without authentication
private data
should not upload a file:
Uncaught AssertionError [ERR_ASSERTION]: false == true
+ expected - actual
-false
+true
at Pumpify.<anonymous> (system-test\storage.js:163:11)
at Pumpify.Duplexify._destroy (node_modules\duplexify\index.js:191:15)
at C:\Users\sawch\dev\nodejs-storage\node_modules\duplexify\index.js:182:10
at _combinedTickCallback …
=> Update to the latest version of nodejs-common and gcs-resumable-upload

src/iam.js
=> refactor(es6): Iam: use es6 class

src/channel.js
=> refactor(es6): Channel: use es6 class

src/file.js, test/file.js
=> fix: signedURL cname (#210)

src/acl.js, src/bucket.js, src/channel.js, src/file.js, src/iam.js, src/index.js, src/notification.js, test/index.js
=> refactor(es6): Refactor constructor pattern as ES6 class

src/acl.js
Existing code defining this.readers, this.owners, ... in Acl and then populating them with methods from the super class AclAccessorRoleMethods violates LSP, it also produces invalid ES6 code.
Addresses the issue with this build (es6 class refactor in `master`):
https://circleci.com/gh/googleapis/nodejs-storage/5702?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- Ran systems test locally and verified it worked
=> fix: move this.[ROLE]s initialization from Acl to AclAccessorRoleMethods

test/acl.ts, test/index.ts
Part of a number of small PRs to address little issues that prevents tests to run.
=> Typescript: require Storage from build location

src/file.ts, test/file.ts
Should be last of the test fixes, after this is merge all tests should pass.
=> TypeScript: make test/file.ts pass

test/acl.ts, test/bucket.ts, test/channel.ts, test/file.ts, test/iam.ts, test/index.ts, test/notification.ts
Does not take care of all linting issues, those would come in a manual PR soon.
=> refactor(ts): run gts fix

test/acl.ts, test/bucket.ts, test/channel.ts, test/file.ts, test/iam.ts, test/index.ts, test/notification.ts
Reverts googleapis/nodejs-storage#297
=> Revert "refactor(ts): function to arrow =>"

src/index.js, system-test/storage.js, test/index.js
Fixes #304 
This introduces `storage.getServiceAccount()`.
=> Add Storage#getServiceAccount().

CHANGELOG.md, package.json
=> Release nodejs-storage v2.0.0

package.json
This should unblock 2.0.0 release.
=> fix(test): broken samples-test script

CHANGELOG.md, package.json, samples/package.json
release and fixes #372 - type declaration doesn't work
=> Release @google-cloud/storage v2.0.1

src/index.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> Improve the types

CHANGELOG.md, package.json
=> Release nodejs-storage v2.0.2

src/file.ts
Marks some optional parameters as such. This PR is by no means exhaustive but at least an incremental improvement.
=> Make some parameters optional

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.0.3

package.json, system-test/storage.ts
TypeScript likes to make compiler changes in semver minor releases that cause compilation errors :)
=> fix: use ~ for typescript (and fix compile errors)

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.1.0

src/acl.ts, src/file.ts, src/index.ts, system-test/storage.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> fix: improve the types

package.json
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> dep: upgrade teeny-request to 3.11.0 with type definitions

src/file.ts, src/iam.ts, system-test/storage.ts, test/file.ts
=> chore(typescript): improve typescript types and update tests

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.2.0

CHANGELOG.md, package.json, samples/package.json
Releasing Object Lifecycle Management
=> feat: release @google-cloud/storage v2.3.0

samples/bucketLock.js
Fixes googleapis/google-cloud-node#2869 (it's a good idea to open an issue first for discussion)
Fixes https://github.com/googleapis/nodejs-storage
=> docs(samples): updated samples code to use async await

samples/package.json, samples/system-test/.eslintrc.yml, samples/system-test/acl.test.js, samples/system-test/bucketLock.test.js, samples/system-test/buckets.test.js, samples/system-test/encryption.test.js, samples/system-test/files.test.js, samples/system-test/iam.test.js, samples/system-test/notifications.test.js, samples/system-test/quickstart.test.js, samples/system-test/requesterPays.test.js
Fixes [googleapis/google-cloud-node#2865](https://github.com/googleapis/google-cloud-node/issues/2865) for this repo
=> refactor: convert sample tests from ava to mocha

package.json, src/file.ts
=> fix(dep): upgrade teeny-request to v3.11.3

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.3.3

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.4.0

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.4.1

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.4.2

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/storage v2.4.3

src/bucket.ts, src/index.ts, src/storage.ts
=> fix(types): fix signatures of listing methods

src/file.ts
=> docs: detailed clarification of 'getSignedUrl' method docs

package.json, system-test/storage.ts, test/acl.ts, test/bucket.ts
=> refactor: remove async devDependency

samples/bucketLock.js, samples/buckets.js
=> refactor(samples): remove 'hasOwnProperty'

system-test/storage.ts
=> tests: fix system tests

package.json
=> fix(deps): use the latest extend

src/bucket.ts, src/file.ts, system-test/storage.ts
=> docs: modernize usage of storage classes

src/storage.ts, test/index.ts
=> feat: allow setting standard Bucket storage class

src/file.ts, test/file.ts
=> refactor: clarify the error message for file#move

samples/quickstart.js
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
=> docs: readme.md to include creation of service account client

src/bucket.ts
=> docs: explain how to use delimiter and prefix

samples/files.js, samples/package.json, samples/system-test/files.test.js, samples/uploadFile.js
Fix: Internal Reference: b/141990380
=> fix: update format for upload sample

src/file.ts
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X ] Ensure the tests and linter pass
- [X ] Code coverage does not decrease (if any source code was changed)
- [X ] Appropriate docs were updated (if necessary)
Fixes #943
=> fix: update PolicyDocument types

src/storage.ts, test/index.ts
=> fix: do not modify constructor options argument

samples/bucketLock.js, samples/getRetentionPolicy.js, samples/system-test/bucketLock.test.js
=> fix: refactor getRetentionPolicy sample into its own file

samples/encryption.js, samples/system-test/encryption.test.js, samples/uploadEncryptedFile.js
=> fix: refactor uploadEncryptedFile sample into its own file

samples/addBucketIamMember.js, samples/removeBucketIamMember.js, samples/system-test/iam.test.js, samples/viewBucketIamMembers.js
These samples were recently edited for IAM conditions, while the samples
refactor is also going on, so those changes were overwritten.
=> fix(samples): fix overwritten IAM conditions sample

conformance-test/test-data/v4SignedUrl.json, conformance-test/v4SignedUrl.ts, linkinator.config.json
Pull in the latest conformance-tests which includes POST policy updates.
POST policy conformance tests are not implemented yet, as it's blocked by #1096.
=> tests: update to googleapis/conformance-tests@a3f959e

src/storage.ts, system-test/storage.ts
=> feat(storage): Add versioning as optional metadata param for createBucket

bin/benchwrapper.js, samples/removeBucketConditionalBinding.js, samples/system-test/iam.test.js, src/file.ts
Add remove conditional binding
=> feat: add remove conditional binding

samples/generateV4SignedPolicy.js
Based on changes requested to -> https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1049
=> fix: add whitespace to generateV4SignedPolicy

package.json
Fixes https://github.com/googleapis/nodejs-storage/issues/1538
=> fix(deps): updated date-and-time dep to 0.14.2
